language: node_js
sudo: false
cache:
  directories:
  - node_modules
node_js:
- 6
before_script:
- npm install -g gulp
script: gulp
notifications:
  email: false
after_success:
- export GIT_TAG=v1.0.$TRAVIS_BUILD_NUMBER
- echo -n $GIT_TAG > v0.1.$TRAVIS_BUILD_NUMBER
- git commit -m "Set build VERSION number to "$GIT_TAG
- git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
- git push --quiet https://$GITHUBKEY@github.com/reedia/skeletonic $GIT_TAG > /dev/null
  2>&1
- echo "${TRAVIS_BRANCH}"
- echo "${TRAVIS_PULL_REQUEST}"
- echo "${TRAVIS_SECURE_ENV_VARS}"
- echo "${TRAVIS_COMMIT}"
- echo ${TRAVIS_BUILD_NUMBER}
- echo ${TRAVIS_REPO_SLUG}
- echo ${GIT_TAG}

before_deploy:
  - echo "Ready to deploy Skeletonic $GIT_TAG"
  - cd dist

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

deploy:
  - provider: releases
    api_key:
      secure: AB76Q+N+MMmPkDkcf5JGpBAsKqAxRE2+dx1/26i0FlYLk3sCuokKDeiIQf1K5YUeH0XbWrNt4aXENh5bqvZKOrDBvKSPamJLY7G/AsEmE7S3zze+CpFQivu+mE9mZe+MDf8lDjQyuEB2W8c6swkulsh5Pv32310yRNw+5PUMe2qBHcmfHPmr3q4HA865khKVjFF6Y7Gw5xFMKMvAw2RRXOuuAWuMMNe2DoNEr94dX8llzLieclg94nEguBUO3BtlmwE6Cxewx9yhUqYLV3AzDLQWuse0s538Zww9Cb6DYT8Q5WsA7GhOrjGoDbYHLSGBwFMtI2QLwVmAXEDAwQDRWix4SNLjDODCt4Qt1Zy2OMDjVLJ5xkdD/H1jv0waC3g7DeAFFjh9cqVosua6HgnQvlvfJFK6bpRxoNCL4Gb1Yz6AGLK1JK5oQKqqdHLMU4je1OZosNdnaOXUtlgi7E2RVDQG3nQsVYg2UWg2v0XoVxi/7MwvZ+xbPeTDBc63hwP/bqpNn3BV9UGoiG7ENPyYCfBSTRX1h8fMCRXr7I94GhKvuqVL5NCBV5FV2YjLV3QUOhVIYEfngsp5DHhapDvJYJc6NrasngTW2dGMwvCQHewVODoOpspS5GeRF08dmpfts7N9l3BJPoGY5uUGMsNyKCF5BxJTDHmFqOshbfV1/6M=
    file_glob: true
    file:
      - dist/*
    skip_cleanup: true
    name: Skeletonic $GIT_TAG
    body: "<strong>Change Log:</strong><br />Release $GIT_TAG created on $(date +'%d/%m/%Y')
      at $(date +'%T')<br />A sleek, lightweight, intuitive and ultra-responsive CSS
      framework. Designed to fit your web life."
    on:
      # all_branches: true
      # tags: true
      repo: reedia/skeletonic
  # - provider: npm
  #   email: $NPM_EMAIL
  #   api_key: $NPM_TOKEN
before_install:
  - openssl aes-256-cbc -K $encrypted_0da74458a2a7_key -iv $encrypted_0da74458a2a7_iv -in id_rsa.enc -out id_rsa -d
